# Generated by Django 5.1.4 on 2024-12-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='client',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='staff_only',
        ),
    ]
