# Generated by Django 5.1.4 on 2025-04-03 12:51

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_faq_client_remove_faq_staff_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prompt', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='clients.client'),
        ),
        migrations.AddField(
            model_name='faq',
            name='staff_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.industry'),
        ),
    ]
