# Generated by Django 5.1.4 on 2024-12-30 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_faq_client_remove_faq_staff_only'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='additional_information',
            field=models.TextField(blank=True, help_text='Late payment penalties or other terms.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='rent amount, item amount, commission or service amount chargged ..', max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='clients.client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='clients.staff'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discounts',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounts you provide if any', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='the total amount including taxes minus discounts ', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_details',
            field=models.TextField(blank=True, help_text='bank account number, bank name, and  till number etc...', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_methods_accepted',
            field=models.TextField(blank=True, help_text='Bank transfer, credit card, paybill, till check, etc.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='property_address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='property_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='property_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='property_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_full_name',
            field=models.CharField(default='pravo', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_phone_number',
            field=models.CharField(default='1234', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference_instructions',
            field=models.TextField(blank=True, help_text='e.g.,Include invoice number as payment reference if required', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_or_item',
            field=models.CharField(default='service', help_text='Brokerage Fee, Property Sale Price, Maintenance Fees, Document Preparation Fees.', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_included',
            field=models.BooleanField(default=False, help_text='check the box or set to true if tax is included in the above amount and vice versa'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.IntegerField(blank=True, help_text='percentage charged tax if included or want to include in total amount if not leave it blank', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(default='titel', max_length=500),
            preserve_default=False,
        ),
    ]
