# Generated by Django 5.1.4 on 2024-12-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_invoice_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='property_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='property_description',
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_type',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale'), ('lease', 'lease')], default='sale', max_length=100),
            preserve_default=False,
        ),
    ]
