# Generated by Django 5.1.4 on 2024-12-31 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_faq_client_remove_faq_staff_only'),
        ('transactions', '0004_rename_property_price_invoice_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('sale', 'Sale Agreement'), ('lease', 'Lease Agreement'), ('rental', 'Rental Agreement'), ('listing', 'Listing Agreement'), ('purchase', 'Purchase Agreement')], help_text='Select the type of contract, e.g., Sale, Lease, or Rental.', max_length=20)),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date when the contract was created.')),
                ('start_date', models.DateField(blank=True, help_text='The start date of the contract, if applicable.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The end date of the contract, if applicable.', null=True)),
                ('seller_landlord_name', models.CharField(help_text='Full name of the seller or landlord.', max_length=255)),
                ('seller_landlord_contact', models.CharField(help_text='Contact information of the seller or landlord.', max_length=255)),
                ('buyer_tenant_name', models.CharField(help_text='Full name of the buyer or tenant.', max_length=255)),
                ('buyer_tenant_contact', models.CharField(help_text='Contact information of the buyer or tenant.', max_length=255)),
                ('agent_license_number', models.CharField(blank=True, help_text='The license number of the agent, if applicable.', max_length=255, null=True)),
                ('property_address', models.TextField(help_text='The full address of the property involved in the contract.')),
                ('property_description', models.TextField(blank=True, help_text='A brief description of the property, including its features.', null=True)),
                ('included_fixtures', models.TextField(blank=True, help_text='List of fixtures and fittings included in the contract.', null=True)),
                ('excluded_fixtures', models.TextField(blank=True, help_text='List of fixtures and fittings excluded from the contract.', null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The total price or rental amount agreed upon.', max_digits=10, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The deposit amount to be paid upfront.', max_digits=10, null=True)),
                ('deposit_due_date', models.DateField(blank=True, help_text='The due date for the deposit payment.', null=True)),
                ('payment_schedule', models.TextField(blank=True, help_text='Details of the payment schedule, if applicable.', null=True)),
                ('taxes_fees', models.TextField(blank=True, help_text='Information about taxes or fees associated with the contract.', null=True)),
                ('contingencies', models.TextField(blank=True, help_text='Conditions that must be met for the contract to proceed.', null=True)),
                ('possession_date', models.DateField(blank=True, help_text='The date when the buyer or tenant can take possession.', null=True)),
                ('default_clauses', models.TextField(blank=True, help_text='Clauses outlining actions in case of default by any party.', null=True)),
                ('termination_conditions', models.TextField(blank=True, help_text='Conditions under which the contract can be terminated.', null=True)),
                ('dispute_resolution', models.TextField(blank=True, help_text='Details on how disputes will be resolved.', null=True)),
                ('governing_law', models.CharField(blank=True, help_text='The legal jurisdiction governing the contract.', max_length=255, null=True)),
                ('non_disclosure_clause', models.BooleanField(default=False, help_text='Indicates if a non-disclosure agreement is included.')),
                ('indemnification_clause', models.BooleanField(default=False, help_text='Indicates if an indemnification clause is included.')),
                ('pets_policy', models.TextField(blank=True, help_text='Details about pet policies, if applicable.', null=True)),
                ('maintenance_responsibilities', models.TextField(blank=True, help_text='Responsibilities for property maintenance.', null=True)),
                ('additional_terms', models.TextField(blank=True, help_text='Any additional terms or conditions for the contract.', null=True)),
                ('attachments', models.FileField(blank=True, help_text='Upload any supporting documents related to the contract.', null=True, upload_to='contract_attachments/')),
                ('seller_landlord_signature', models.ImageField(blank=True, help_text='Upload the signature of the seller or landlord.', null=True, upload_to='signatures/')),
                ('buyer_tenant_signature', models.ImageField(blank=True, help_text='Upload the signature of the buyer or tenant.', null=True, upload_to='signatures/')),
                ('witness_signature', models.ImageField(blank=True, help_text='Upload the signature of a witness, if required.', null=True, upload_to='signatures/')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='clients.staff')),
            ],
        ),
    ]
