# Generated by Django 5.1.4 on 2024-12-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_realestatecontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatecontract',
            name='agent_name',
            field=models.CharField(blank=True, help_text='Full name of the buyer or tenant.', max_length=255, null=True),
        ),
    ]
