# Generated by Django 5.1.4 on 2024-12-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_realestatecontract_agent_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractsAgreement',
        ),
    ]
