# Generated by Django 5.1.4 on 2024-12-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_delete_contractsagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatecontract',
            name='agent_contact',
            field=models.CharField(blank=True, help_text='Full name of the buyer or tenant.', max_length=255, null=True),
        ),
    ]
