# Generated by Django 5.1.4 on 2024-12-31 13:01

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_realestatecontract_agent_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatecontract',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='additional_terms',
            field=tinymce.models.HTMLField(blank=True, help_text='Any additional terms or conditions for the contract.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='agent_contact',
            field=models.CharField(blank=True, help_text='agent Contact .', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='agent_name',
            field=models.CharField(blank=True, help_text='agent Full name ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='contingencies',
            field=tinymce.models.HTMLField(blank=True, help_text='Conditions that must be met for the contract to proceed.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='default_clauses',
            field=tinymce.models.HTMLField(blank=True, help_text='Clauses outlining actions in case of default by any party.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='dispute_resolution',
            field=tinymce.models.HTMLField(blank=True, help_text='Details on how disputes will be resolved.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='excluded_fixtures',
            field=tinymce.models.HTMLField(blank=True, help_text='List of fixtures and fittings excluded from the contract.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='included_fixtures',
            field=tinymce.models.HTMLField(blank=True, help_text='List of fixtures and fittings included in the contract.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='maintenance_responsibilities',
            field=tinymce.models.HTMLField(blank=True, help_text='Responsibilities for property maintenance.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='payment_schedule',
            field=tinymce.models.HTMLField(blank=True, help_text='Details of the payment schedule, if applicable.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='pets_policy',
            field=tinymce.models.HTMLField(blank=True, help_text='Details about pet policies, if applicable.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='property_address',
            field=tinymce.models.HTMLField(blank=True, help_text='The full address of the property involved in the contract.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='property_description',
            field=tinymce.models.HTMLField(blank=True, help_text='A brief description of the property, including its features.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='taxes_fees',
            field=tinymce.models.HTMLField(blank=True, help_text='Information about taxes or fees associated with the contract.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatecontract',
            name='termination_conditions',
            field=tinymce.models.HTMLField(blank=True, help_text='Conditions under which the contract can be terminated.', null=True),
        ),
    ]
