# Generated by Django 5.1.4 on 2024-12-27 07:59

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='customers')),
                ('message', tinymce.models.HTMLField()),
                ('useful_count', models.IntegerField(default=0, help_text='number of likes')),
                ('not_useful_count', models.IntegerField(default=0, help_text='if this number exceeds 10 we remove the comment from appearing to the website')),
                ('useful', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('funnel_stage', models.CharField(choices=[('awareness', 'awareness'), ('interest', 'interest'), ('decision', 'decision'), ('purchase', 'purchase'), ('active', 'active'), ('dormant', 'dormant')], default='interest', max_length=50)),
                ('phone_number', models.CharField(help_text='must write your number in international formart including you country code and excluding (+) example 254765342134 makesure it doesnt have + sign', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('last_interaction_summary', tinymce.models.HTMLField(blank=True, null=True)),
                ('refferal_source', models.CharField(choices=[('shop', 'shop'), ('call', 'call'), ('facebook', 'facebook'), ('friend', 'friend'), ('online', 'online')], default='shop', help_text='how customer found out about us', max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_talked', models.DateField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'customer'), ('AI', 'AI')], max_length=50)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coversations', to='clients.client')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coversations', to='clients.staff')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('history_status', models.CharField(choices=[('view', 'view'), ('add to cart', 'add to cart'), ('purchased', 'purchased')], default='view', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historys', to='clients.client')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', tinymce.models.HTMLField()),
                ('replied', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNicheSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(help_text='think of this as diffrent niches customer can be', max_length=200)),
                ('outreach_message', models.TextField(help_text='this message must be created first on facebook then be approved, if not approved whatsapp wont send them', max_length=700)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Niches', to='clients.client')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='niche',
            field=models.ForeignKey(blank=True, help_text='customer niche segments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customernichesegment'),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_place', models.CharField(choices=[('your shop', 'your shop'), ('customers shop', 'customers shop'), ('call', 'call'), ('online meeting', 'online meeting')], help_text='where was the interaction held', max_length=50)),
                ('customer_sales_funnel_stage', models.CharField(blank=True, choices=[('awareness', 'awareness'), ('interest', 'interest'), ('decision', 'decision'), ('purchase', 'purchase'), ('active', 'active'), ('dormant', 'dormant')], max_length=100, null=True)),
                ('conversation_summary', tinymce.models.HTMLField(blank=True, max_length=1000, null=True)),
                ('next_step', models.CharField(max_length=300)),
                ('next_step_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='clients.client')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='clients.staff')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='customers')),
                ('customer_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_stars', models.IntegerField(default=5)),
                ('message', tinymce.models.HTMLField()),
                ('approved', models.BooleanField(default=True, help_text='check this if you want testimony to appear on website')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='clients.client')),
            ],
        ),
    ]
