# Generated by Django 5.1.4 on 2025-04-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(help_text='must write your number in international formart including you country code and excluding (+) example 254765342134 makesure it doesnt have + sign', max_length=20),
        ),
    ]
