# Generated by Django 5.0.1 on 2024-09-27 08:55

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=500)),
                ('task_stage', models.CharField(blank=True, choices=[('lead capturing', 'lead capturing'), ('finding out more', 'finding out more'), ('training', 'training'), ('reaching out', 'reaching out'), ('follow-up', 'follow-up')], max_length=100, null=True)),
                ('repeat', models.CharField(choices=[('once', 'once'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='once', max_length=100)),
                ('days_to_repeat', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56, null=True)),
                ('task_date', models.DateField(help_text='if selected repeat choose start date')),
                ('done', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
            ],
        ),
    ]
